//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cart_ID { get; set; }
        public Nullable<int> user_ID { get; set; }
        public Nullable<System.DateTime> create_AT { get; set; }
    
        public virtual CartItem CartItem { get; set; }
        public virtual User User { get; set; }
    }
}
