//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int cart_Item_ID { get; set; }
        public Nullable<int> cart_ID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
