//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int review_ID { get; set; }
        public Nullable<int> user_ID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> create_At { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
